//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateTable
    {
        public DateTable()
        {
            this.orderFromSupplierTable = new HashSet<orderFromSupplierTable>();
        }
    
        public int Id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
    
        public virtual ICollection<orderFromSupplierTable> orderFromSupplierTable { get; set; }
    }
}
