//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesTable
    {
        public int Id { get; set; }
        public Nullable<int> water { get; set; }
        public Nullable<int> elecricity { get; set; }
        public Nullable<int> materials { get; set; }
        public Nullable<int> workers_salary { get; set; }
        public Nullable<int> office_workers_salary { get; set; }
    }
}
