//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesTable
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual supplierTable supplierTable { get; set; }
    }
}
