//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class managingDataBaseEntities : DbContext
    {
        public managingDataBaseEntities()
            : base("name=managingDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostumersTable> CostumersTable { get; set; }
        public virtual DbSet<CurrentExpendsTable> CurrentExpendsTable { get; set; }
        public virtual DbSet<currentExpendsTypeTable> currentExpendsTypeTable { get; set; }
        public virtual DbSet<EmployeeTable> EmployeeTable { get; set; }
        public virtual DbSet<orderDetailsTable> orderDetailsTable { get; set; }
        public virtual DbSet<orderFromSupplierDetailTable> orderFromSupplierDetailTable { get; set; }
        public virtual DbSet<orderFromSupplierTable> orderFromSupplierTable { get; set; }
        public virtual DbSet<OrdersTable> OrdersTable { get; set; }
        public virtual DbSet<supplierTable> supplierTable { get; set; }
        public virtual DbSet<variableExpendsTable> variableExpendsTable { get; set; }
        public virtual DbSet<variableExpendsTypeTable> variableExpendsTypeTable { get; set; }
    }
}
