//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsTable
    {
        public MaterialsTable()
        {
            this.MatrialPrice = new HashSet<MatrialPrice>();
            this.MaterialsTable1 = new HashSet<MaterialsTable>();
            this.orderFromSupplierDetailTable = new HashSet<orderFromSupplierDetailTable>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string materialType { get; set; }
        public Nullable<int> materialPrice_id { get; set; }
        public string notes { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual ICollection<MatrialPrice> MatrialPrice { get; set; }
        public virtual ICollection<MaterialsTable> MaterialsTable1 { get; set; }
        public virtual MaterialsTable MaterialsTable2 { get; set; }
        public virtual ICollection<orderFromSupplierDetailTable> orderFromSupplierDetailTable { get; set; }
    }
}
