//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderFromSupplierTable
    {
        public orderFromSupplierTable()
        {
            this.BuyingFromSupplier = new HashSet<BuyingFromSupplier>();
        }
    
        public int Id { get; set; }
        public string material { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> meters { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
    
        public virtual ICollection<BuyingFromSupplier> BuyingFromSupplier { get; set; }
        public virtual supplierTable supplierTable { get; set; }
    }
}
