//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        public OrdersTable()
        {
            this.BuyingTable = new HashSet<BuyingTable>();
        }
    
        public int Id { get; set; }
        public Nullable<int> costumer_id { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> costPrice { get; set; }
        public string invoiceNumber { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> date_id_order { get; set; }
        public Nullable<int> date_id_supplying { get; set; }
        public string shipping_address { get; set; }
        public string shipping_number { get; set; }
        public string reception_number { get; set; }
    
        public virtual ICollection<BuyingTable> BuyingTable { get; set; }
        public virtual CostumersTable CostumersTable { get; set; }
        public virtual DateTable DateTable { get; set; }
        public virtual DateTable DateTable1 { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
