//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderFromSupplierTable
    {
        public orderFromSupplierTable()
        {
            this.supplierTable = new HashSet<supplierTable>();
        }
    
        public int Id { get; set; }
        public Nullable<int> dateOfOrder_id { get; set; }
        public string material { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> meters { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual DateTable DateTable { get; set; }
        public virtual ICollection<supplierTable> supplierTable { get; set; }
    }
}
