//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        public int Id { get; set; }
        public Nullable<int> costumer_id { get; set; }
        public string invoiceNumber { get; set; }
        public string shipping_number { get; set; }
        public string reception_number { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> orderDetail_id { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> supplyingDate { get; set; }
        public string notes { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual CostumersTable CostumersTable { get; set; }
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual orderDetailsTable orderDetailsTable { get; set; }
    }
}
