//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierTable
    {
        public supplierTable()
        {
            this.orderFromSupplierDetailTable = new HashSet<orderFromSupplierDetailTable>();
        }
    
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string country { get; set; }
        public string phoneNumber { get; set; }
        public string E_mail { get; set; }
        public string notes { get; set; }
        public string address { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual ICollection<orderFromSupplierDetailTable> orderFromSupplierDetailTable { get; set; }
    }
}
